import Tile from './Tile'

export default function Instructions() {
    return (
        <div className="help">

            <p>The goal of Mastermind is to guess the secret code, a sequence of 4 colored pegs generated by the Mastermind. For example, here's a secret code the Mastermind might think of...</p>
            <Tile active="active" className="tile board" value="c0"></Tile>
            <Tile active="active" className="tile board" value="c4"></Tile>
            <Tile active="active" className="tile board" value="c3"></Tile>
            <Tile active="active" className="tile board" value="c1"></Tile>
            <hr></hr>
            <p>Using the colors, create a pattern and click 'guess' to see how close you are. This is what we might guess the code is...</p>
            <Tile active="active" className="tile board" value="c1"></Tile>
            <Tile active="active" className="tile board" value="c3"></Tile>
            <Tile active="active" className="tile board" value="c5"></Tile>
            <Tile active="active" className="tile board" value="c1"></Tile>
            <hr></hr>

            <p>Your guess will be checcked, and the evaluataion will appear in the four small pegs on the right of the board. In this case, the evaluation would be...</p>
            <div className="row">
                <Tile active="active" className="tile eval" value="c6"></Tile>
                <Tile active="active" className="tile eval" value="c7"></Tile>
            </div>
            <div className="row">
                <Tile active="active" className="tile eval" value=""></Tile>
                <Tile active="active" className="tile eval" value=""></Tile>
            </div>
            <p>
                <Tile active="active" className="tile eval" value="c6"></Tile> means one peg in our guess is the right color and is in the right place (the 4th tile in our guess)
            </p>
            <p>
                <Tile active="active" className="tile eval" value="c7"></Tile> means one peg in our guess is the right color but is in the wrong place (the 2nd tile)
            </p>
            <p>
                <Tile active="active" className="tile eval" value=""></Tile> means one peg in our guess is not the right color and therefore not in the secret code (the 1st and 3rd tiles)
            </p>
            <p>*Note: the order of the evaluation pegs does not matter</p>
            <hr></hr>
            <p>Try to win before you run out of moves. When you guess the code, the evaluation pegs should look like:</p>

            <div className="row">
                <Tile active="active" className="tile eval" value="c6"></Tile>
                <Tile active="active" className="tile eval" value="c6"></Tile>
            </div>
            <div className="row">
                <Tile active="active" className="tile eval" value="c6"></Tile>
                <Tile active="active" className="tile eval" value="c6"></Tile>
            </div>
            <br></br>
        </div>
    );
}